import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { api } from '../services/api';
import { LoadingSkeleton } from '../components/LoadingSkeleton';
import {
  FileText,
  Upload,
  Sparkles,
  Copy,
  Download,
  Bookmark,
  Check,
  MessageSquare,
  CheckSquare,
  Loader2,
  FileCheck,
  AlertCircle,
} from 'lucide-react';

export default function SummaryPage() {
  const navigate = useNavigate();

  const [activeTab, setActiveTab] = useState('paste'); // 'paste' | 'upload'
  const [text, setText] = useState('');
  const [file, setFile] = useState(null);
  const [length, setLength] = useState('medium'); // 'short' | 'medium' | 'detailed'
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');

  const handleSummarize = async () => {
    setError('');

    if (activeTab === 'paste') {
      if (!text.trim() || text.length < 20) {
        setError('Please paste educational text of at least 20 characters to summarize.');
        return;
      }

      setLoading(true);
      try {
        const data = await api.summarizeText({ text, length });
        setResult(data);
      } catch (err) {
        setError(err.message || 'Summarization failed.');
      } finally {
        setLoading(false);
      }
    } else {
      if (!file) {
        setError('Please select a PDF or TXT file to upload.');
        return;
      }

      setLoading(true);
      try {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('length', length);
        const data = await api.uploadAndSummarize(formData);
        
        // Normalize uploaded output into standard tabs
        setResult({
          summary: data.summary,
          key_points: ["Extracted from uploaded document " + data.filename],
          important_terms: [],
          revision_notes: "Key notes compiled from document.",
          one_minute_revision: data.summary.slice(0, 300) + "...",
        });
      } catch (err) {
        setError(err.message || 'File upload summarization failed.');
      } finally {
        setLoading(false);
      }
    }
  };

  const handleCopy = () => {
    if (!result) return;
    const fullText = `# Summary\n${result.summary}\n\n## Key Points\n${result.key_points.map(p => `- ${p}`).join('\n')}\n\n## Revision\n${result.one_minute_revision}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!result) return;
    const content = `# EduGenie Smart Summary\n\n## Overview\n${result.summary}\n\n## Key Points\n${result.key_points.map(p => `- ${p}`).join('\n')}\n\n## One-Minute Revision\n${result.one_minute_revision}\n\nGenerated by EduGenie AI`;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `edugenie-summary-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    if (!result) return;
    try {
      await api.saveItem({
        item_type: 'summary',
        title: `Summary: ${result.summary.slice(0, 45)}...`,
        content: result.summary,
        metadata_json: { length, key_points: result.key_points },
      });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleAskFollowUp = () => {
    if (!result) return;
    navigate(`/chat?q=${encodeURIComponent(`I have a doubt about this summarized content: ${result.summary.slice(0, 150)}`)}`);
  };

  const handleGenerateQuizFromSummary = () => {
    if (!result) return;
    navigate(`/quiz?topic=${encodeURIComponent(result.key_points[0] || 'Summarized Topics')}`);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-200">
      
      {/* Header */}
      <div className="text-center sm:text-left">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300 text-xs font-semibold mb-2">
          <FileText className="w-3.5 h-3.5" />
          <span>Intelligent Content Condensation</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">
          Smart Educational Summarizer & Document Learner
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
          Paste academic passages or upload PDF/TXT notes to extract key takeaways, exam notes, and flashcard terms.
        </p>
      </div>

      {error && (
        <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 text-xs text-red-600 dark:text-red-400 flex items-center gap-2">
          <AlertCircle className="w-4 h-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Input Module */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-200/80 dark:border-slate-800/80 shadow-lg space-y-6">
        
        {/* Mode Toggle Tabs */}
        <div className="flex gap-2 p-1 bg-slate-100 dark:bg-slate-800/80 rounded-2xl max-w-xs">
          <button
            onClick={() => setActiveTab('paste')}
            className={`flex-1 py-2 text-xs font-semibold rounded-xl transition-all ${
              activeTab === 'paste'
                ? 'bg-white dark:bg-slate-900 text-primary-600 dark:text-primary-400 shadow-sm'
                : 'text-slate-500'
            }`}
          >
            Paste Text
          </button>
          <button
            onClick={() => setActiveTab('upload')}
            className={`flex-1 py-2 text-xs font-semibold rounded-xl transition-all ${
              activeTab === 'upload'
                ? 'bg-white dark:bg-slate-900 text-primary-600 dark:text-primary-400 shadow-sm'
                : 'text-slate-500'
            }`}
          >
            Upload PDF / TXT
          </button>
        </div>

        {activeTab === 'paste' ? (
          <div>
            <textarea
              rows={6}
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste long textbook chapters, lecture notes, or research papers here..."
              className="w-full p-4 rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/70 dark:bg-slate-800/70 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 font-sans"
            />
          </div>
        ) : (
          <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-3xl p-8 text-center bg-slate-50/50 dark:bg-slate-900/30">
            <Upload className="w-10 h-10 text-slate-400 mx-auto mb-3" />
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
              {file ? file.name : "Select or drag a PDF or TXT file"}
            </p>
            <p className="text-xs text-slate-400 mt-1 mb-4">
              Supported formats: .pdf, .txt (up to 10MB)
            </p>
            <label className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 cursor-pointer hover:bg-slate-50">
              <span>Browse Files</span>
              <input
                type="file"
                accept=".pdf,.txt"
                onChange={(e) => setFile(e.target.files[0])}
                className="hidden"
              />
            </label>
          </div>
        )}

        {/* Options & Action */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-500">Summary Scope:</span>
            <div className="flex rounded-xl bg-slate-100 dark:bg-slate-800/80 p-1">
              {[
                { id: 'short', label: 'Concise (Quick)' },
                { id: 'medium', label: 'Balanced' },
                { id: 'detailed', label: 'Detailed / Deep' },
              ].map(opt => (
                <button
                  key={opt.id}
                  onClick={() => setLength(opt.id)}
                  className={`px-3 py-1 text-xs font-semibold rounded-lg transition-all ${
                    length === opt.id
                      ? 'bg-white dark:bg-slate-900 text-primary-600 dark:text-primary-400 shadow-sm'
                      : 'text-slate-500'
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={handleSummarize}
            disabled={loading}
            className="px-6 py-2.5 rounded-xl bg-primary-600 hover:bg-primary-700 text-white font-semibold text-xs sm:text-sm shadow-md shadow-primary-500/25 flex items-center justify-center gap-2 transition-all disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            <span>Condense & Summarize</span>
          </button>
        </div>

      </div>

      {/* Loading Skeleton */}
      {loading && (
        <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-200/80 dark:border-slate-800/80 shadow-md">
          <div className="flex items-center gap-2 mb-6 text-sm font-semibold text-primary-600">
            <Loader2 className="w-4 h-4 animate-spin" />
            <span>EduGenie is analyzing document structure and extracting key points...</span>
          </div>
          <LoadingSkeleton lines={6} />
        </div>
      )}

      {/* Summary Output */}
      {result && !loading && (
        <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-200/80 dark:border-slate-800/80 shadow-xl space-y-6">
          
          {/* Action Toolbar */}
          <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-200 dark:border-slate-800">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400">
                Processed Summary
              </span>
              <h3 className="text-base font-bold text-slate-900 dark:text-white">
                Extracted Educational Insights
              </h3>
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <button
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-50"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>

              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-50"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .MD</span>
              </button>

              <button
                onClick={handleSave}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-primary-600 hover:bg-primary-700 text-white text-xs font-semibold shadow-sm"
              >
                {saved ? <Check className="w-3.5 h-3.5" /> : <Bookmark className="w-3.5 h-3.5" />}
                <span>{saved ? 'Saved' : 'Save'}</span>
              </button>
            </div>
          </div>

          {/* Section 1: Summary Text */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
              📋 Summary
            </h4>
            <div className="markdown-body p-4 rounded-2xl bg-white/60 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {result.summary}
              </ReactMarkdown>
            </div>
          </div>

          {/* Section 2: Key Points */}
          {result.key_points && result.key_points.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                🔑 Key Points
              </h4>
              <ul className="space-y-2">
                {result.key_points.map((point, idx) => (
                  <li key={idx} className="p-3 rounded-xl bg-white/60 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 text-xs sm:text-sm font-medium text-slate-700 dark:text-slate-200 flex items-start gap-2.5">
                    <span className="w-5 h-5 rounded-md bg-primary-100 dark:bg-primary-950 text-primary-600 dark:text-primary-300 text-xs font-bold flex items-center justify-center shrink-0">
                      {idx + 1}
                    </span>
                    <span className="mt-0.5">{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Section 3: One-Minute Rapid Revision */}
          {result.one_minute_revision && (
            <div className="p-5 rounded-2xl bg-amber-50/70 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/60 space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />
                <span>⚡ 60-Second Exam Revision</span>
              </h4>
              <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-200 leading-relaxed font-medium">
                {result.one_minute_revision}
              </p>
            </div>
          )}

          {/* Next Educational Steps */}
          <div className="pt-4 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3">
            <span className="text-xs text-slate-400">+5 XP awarded for summarization</span>
            
            <div className="flex items-center gap-2">
              <button
                onClick={handleAskFollowUp}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-primary-300 dark:border-primary-700 text-xs font-semibold text-primary-600 dark:text-primary-400 hover:bg-primary-50"
              >
                <MessageSquare className="w-3.5 h-3.5" />
                <span>Ask AI About This</span>
              </button>

              <button
                onClick={handleGenerateQuizFromSummary}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-sm"
              >
                <CheckSquare className="w-3.5 h-3.5" />
                <span>Generate Practice Quiz</span>
              </button>
            </div>
          </div>

        </div>
      )}

    </div>
  );
}
